### ISSUE TITLE
MIME type ('application/problem+json') is not executable, and strict MIME type checking is enabled

### ISSUE THREAD

**Issue by galaxy2017** [halo-sigs/plugin-editor-hyperlink-card#13]
GET https://site.url/plugins/editor-hyperlink-card/assets/static/hyperlink-card.iife.js?version=1.0.3 net::ERR_ABORTED 404 (Not Found)

Refused to execute script from 'https://site.url/plugins/editor-hyperlink-card/assets/static/hyperlink-card.iife.js?version=1.0.3' because its MIME type ('application/problem+json') is not executable, and strict MIME type checking is enabled.

**Comment by ruibaby** [comment]
/triage duplicate

https://github.com/halo-sigs/plugin-editor-hyperlink-card/issues/7
