### ISSUE TITLE
B站视频无法生成卡片

### ISSUE THREAD

**Issue by yblpoi** [halo-sigs/plugin-editor-hyperlink-card#3]
复现方法：
- 在文章编辑中插入一条B站的视频链接
- 点击转换为卡片
- 链接并没有正常转换为卡片效果，而是显示链接

图片
![image](https://github.com/halo-sigs/plugin-editor-hyperlink-card/assets/66136793/9ef66cf5-92c7-4879-9c29-bca866f1dc03)

上面一条为普通链接的效果，下面一条则是卡片生成失败的效果

**Comment by ruibaby** [comment]
可以复现。

/kind bug
