### ISSUE TITLE
可以支持其他markdown编辑器吗

### ISSUE THREAD

**Issue by wenjing-xin** [halo-sigs/plugin-editor-hyperlink-card#5]
目前只能在默认编辑器中使用，我想在 Vditor 编辑器中使用它

**Comment by ruibaby** [comment]
已经在 README 中添加[作为标签使用](https://github.com/halo-sigs/plugin-editor-hyperlink-card?tab=readme-ov-file#%E4%BD%9C%E4%B8%BA%E6%A0%87%E7%AD%BE%E4%BD%BF%E7%94%A8)的说明，理论上可以插入到网站上的任意位置。所以在其他编辑器中（如果支持插入 HTML 标签）中使用是可行的，但未其他编辑器不是此插件的主动支持范围。

**Comment by wenjing-xin** [comment]
> 已经在 README 中添加[作为标签使用](https://github.com/halo-sigs/plugin-editor-hyperlink-card?tab=readme-ov-file#%E4%BD%9C%E4%B8%BA%E6%A0%87%E7%AD%BE%E4%BD%BF%E7%94%A8)的说明，理论上可以插入到网站上的任意位置。所以在其他编辑器中（如果支持插入 HTML 标签）中使用是可行的，但未其他编辑器不是此插件的主动支持范围。

使用的时候在markdown编辑器后台可以渲染，但是文章页面就报错 
![image](https://github.com/halo-sigs/plugin-editor-hyperlink-card/assets/130843859/12227aef-db68-4e79-b62f-0d093ba86785)

**Comment by ruibaby** [comment]
> > 已经在 README 中添加[作为标签使用](https://github.com/halo-sigs/plugin-editor-hyperlink-card?tab=readme-ov-file#%E4%BD%9C%E4%B8%BA%E6%A0%87%E7%AD%BE%E4%BD%BF%E7%94%A8)的说明，理论上可以插入到网站上的任意位置。所以在其他编辑器中（如果支持插入 HTML 标签）中使用是可行的，但未其他编辑器不是此插件的主动支持范围。
> 
> 使用的时候在markdown编辑器后台可以渲染，但是文章页面就报错 ![image](https://private-user-images.githubusercontent.com/130843859/339996609-12227aef-db68-4e79-b62f-0d093ba86785.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NjIzOTcsIm5iZiI6MTcxODQ2MjA5NywicGF0aCI6Ii8xMzA4NDM4NTkvMzM5OTk2NjA5LTEyMjI3YWVmLWRiNjgtNGU3OS1iNjJmLTBkMDkzYmE4Njc4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQxNDM0NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWZhMWU4MzNjYTkwY2IxYmZiNDY3Mzk0OTYxYWMyMGZmOGIzYTc4ODE5NmU5ZmEwMDc3NjBmMjdmOWNiYjk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ikQvHhf0DL0VLvfk3Hv8tVlDfC2CWB5krjoE2jHGW_E)

卸载，重新安装 1.0.2，之前因为 CI 问题，发布到应用市场的 jar 包有问题。
