### ISSUE TITLE
1.0.3前台无法正常解析卡片

### ISSUE THREAD

**Issue by likesrt** [halo-sigs/plugin-editor-hyperlink-card#7]
hyperlink-card.iife.js  资源404

**Comment by FHZDCJ** [comment]
我这里也发现了同样的问题

**Comment by ruibaby** [comment]
卸载插件，然后从应用市场重新安装，之前的 CI 构建流程有问题，导致没有正常生成 js。

**Comment by likesrt** [comment]
> 卸载插件，然后从应用市场重新安装，之前的 CI 构建流程有问题，导致没有正常生成 js。

已正常解析卡片
